version: "3.9"

services:
  app:
    build: .
    container_name: eos-actions-app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/eos-actions
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
